{
 "title": "fornello",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "arduino.fornello.temp" }
   ]
  },
  {
   "title": "Ambiente",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(arduino.fornello.tAvg)"
    },
    {
     "target": "aliasByMetric(arduino.fornello.tEnv)"
    }
   ]
  },
  {
   "title": "Fiamma",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "arduino.fornello.flame" }
   ]
  },
  {
   "title": "Presente",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "arduino.fornello.away" }
   ]
  },
  {
   "title": "Log seriale",
   "type": "logs",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{source=\"serialport\"} |= ``"
    }
   ]
  }
 ]
}